plot:
    spectrum:
        use_cols: [0, 1]
        figure_size: [7, 5]
        xcolumn: "Wavelength (nm)"
        ycolumn: "Abs"
        xlabel: "Wavelength (nm)"
        ylabel: "Absorbance (A.U.)"
        xlimit: [300, 500]
        ylimit:
        skip_header: 1
        legend_location: "upper left"
        title:
    kinetics:
        fit: True
        model: "exp"
        init_params:
            exp1: [1, -1, 1]
            exp2: [1, 1, 0, 0]
            linear: [1, 1]
        use_cols: [0, 1]
        figure_size: [7, 5]
        xcolumn: "Time (min)"
        ycolumn: "Abs"
        xlabel: "Time (min)"
        ylabel: "Absorbance (A.U.)"
        xlimit:
        ylimit:
        skip_header: 1
        legend_location: "lower right"
        title:
        time_unit: "minute"
